In [5]:
# imports
import numpy as np
import pandas as pd

In [250]:
# add dataFrames
crime = pd.read_csv('./data/crime.csv')
offense_codes = pd.ExcelFile('./data/rmsoffensecodes.xlsx').parse('offense_codes (1)')
#print (offense_codes.head())
#print('\n--------------------\n')
print (crime.head())

  INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0      I172101695          3301                  Verbal Disputes
1      I172101688          3301                  Verbal Disputes
2      I172101687          3802  Motor Vehicle Accident Response
3      I172101683          3301                  Verbal Disputes
4      I172101681           802                   Simple Assault

               OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0                   VERBAL DISPUTE       B2            304      NaN
1                   VERBAL DISPUTE       D4            165      NaN
2  M/V ACCIDENT - PROPERTY ï¿½DAMAGE       B3            458      NaN
3                   VERBAL DISPUTE      E18            555      NaN
4         ASSAULT SIMPLE - BATTERY      C11            334      NaN

      OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0  2017-12-07 18:09:00  2017     12    Thursday    18  Part Three
1  2017-12-07 21:25:00  2017     12    Thursday    21  Part Three
2  2017-12-07 21:23:00  2017     12    Thursday    21  Part Three
3  2017-12-07 21:04:00  2017     12    Thursday    21  Part Three
4  2017-12-07 20:54:00  2017     12    Thursday    20    Part Two

          STREET        Lat       Long                     Location
0  WASHINGTON ST  42.319440 -71.094675  (42.31943966, -71.09467467)
1  E BERKELEY ST  42.343228 -71.063431  (42.34322816, -71.06343087)
2  BLUE HILL AVE  42.302389 -71.085394  (42.30238881, -71.08539388)
3       GREW AVE  42.275100 -71.121781  (42.27510049, -71.12178148)
4      HENDRY ST  42.309459 -71.065146  (42.30945933, -71.06514623)

In [172]:
temp = crime.merge(offense_codes,'outer',left_on='OFFENSE_CODE',right_on='CODE')
print (temp.head())

  INCIDENT_NUMBER  OFFENSE_CODE OFFENSE_CODE_GROUP OFFENSE_DESCRIPTION  \
0      I172101695        3301.0    Verbal Disputes      VERBAL DISPUTE
1      I172101695        3301.0    Verbal Disputes      VERBAL DISPUTE
2      I172101688        3301.0    Verbal Disputes      VERBAL DISPUTE
3      I172101688        3301.0    Verbal Disputes      VERBAL DISPUTE
4      I172101683        3301.0    Verbal Disputes      VERBAL DISPUTE

  DISTRICT REPORTING_AREA SHOOTING     OCCURRED_ON_DATE    YEAR  MONTH  \
0       B2            304      NaN  2017-12-07 18:09:00  2017.0   12.0
1       B2            304      NaN  2017-12-07 18:09:00  2017.0   12.0
2       D4            165      NaN  2017-12-07 21:25:00  2017.0   12.0
3       D4            165      NaN  2017-12-07 21:25:00  2017.0   12.0
4      E18            555      NaN  2017-12-07 21:04:00  2017.0   12.0

  DAY_OF_WEEK  HOUR    UCR_PART         STREET        Lat       Long  \
0    Thursday  18.0  Part Three  WASHINGTON ST  42.319440 -71.094675
1    Thursday  18.0  Part Three  WASHINGTON ST  42.319440 -71.094675
2    Thursday  21.0  Part Three  E BERKELEY ST  42.343228 -71.063431
3    Thursday  21.0  Part Three  E BERKELEY ST  42.343228 -71.063431
4    Thursday  21.0  Part Three       GREW AVE  42.275100 -71.121781

                      Location  CODE            NAME
0  (42.31943966, -71.09467467)  3301  VERBAL DISPUTE
1  (42.31943966, -71.09467467)  3301  VERBAL DISPUTE
2  (42.34322816, -71.06343087)  3301  VERBAL DISPUTE
3  (42.34322816, -71.06343087)  3301  VERBAL DISPUTE
4  (42.27510049, -71.12178148)  3301  VERBAL DISPUTE

In [71]:
crime.columns

Index([u'INCIDENT_NUMBER', u'OFFENSE_CODE', u'OFFENSE_CODE_GROUP',
       u'OFFENSE_DESCRIPTION', u'DISTRICT', u'REPORTING_AREA', u'SHOOTING',
       u'OCCURRED_ON_DATE', u'YEAR', u'MONTH', u'DAY_OF_WEEK', u'HOUR',
       u'UCR_PART', u'STREET', u'Lat', u'Long', u'Location'],
      dtype='object')

In [257]:
null_columns = crime.columns[crime.isnull().any()]
crime[null_columns].isnull().sum()
print (null_columns) 
print (crime[null_columns].isnull().sum()) # count of all nul columns
#print(crime[crime["STREET"].isnull()][null_columns]) #// find all columns with null
#print(crime[crime.isnull().any(axis=1)][null_columns].head())
crime.isnull().any(axis=0) #// list all columns where there are null values
(crime.isnull().any(axis=0) == False).sum() # count amount of coulumns that are False (do not have )

Index([u'DISTRICT', u'SHOOTING', u'UCR_PART', u'STREET', u'Lat', u'Long'], dtype='object')
DISTRICT      1290
SHOOTING    245382
UCR_PART        75
STREET        9868
Lat          15071
Long         15071
dtype: int64

11

In [263]:
# find amount of crimes with shooting
print (crime["SHOOTING"].notnull().sum())

785

In [72]:
crime.index = crime.pop('INCIDENT_NUMBER')
crime.head()

,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
INCIDENT_NUMBER,,,,,,,,,,,,,,,,
I172101695,3301,Verbal Disputes,VERBAL DISPUTE,B2,304,NaN,2017-12-07 18:09:00,2017,12,Thursday,18,Part Three,WASHINGTON ST,42.319440,-71.094675,"(42.31943966, -71.09467467)"
I172101688,3301,Verbal Disputes,VERBAL DISPUTE,D4,165,NaN,2017-12-07 21:25:00,2017,12,Thursday,21,Part Three,E BERKELEY ST,42.343228,-71.063431,"(42.34322816, -71.06343087)"
I172101687,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,B3,458,NaN,2017-12-07 21:23:00,2017,12,Thursday,21,Part Three,BLUE HILL AVE,42.302389,-71.085394,"(42.30238881, -71.08539388)"
I172101683,3301,Verbal Disputes,VERBAL DISPUTE,E18,555,NaN,2017-12-07 21:04:00,2017,12,Thursday,21,Part Three,GREW AVE,42.275100,-71.121781,"(42.27510049, -71.12178148)"
I172101681,802,Simple Assault,ASSAULT SIMPLE - BATTERY,C11,334,NaN,2017-12-07 20:54:00,2017,12,Thursday,20,Part Two,HENDRY ST,42.309459,-71.065146,"(42.30945933, -71.06514623)"

In [73]:
crime.describe()

,OFFENSE_CODE,YEAR,MONTH,HOUR,Lat,Long
count,246167.000000,246167.000000,246167.000000,246167.000000,231096.000000,231096.000000
mean,2308.499519,2016.164900,6.991766,13.133751,42.232636,-70.937532
std,1187.565113,0.755625,3.252440,6.297211,1.970567,3.187515
min,111.000000,2015.000000,1.000000,0.000000,-1.000000,-71.178674
25%,1001.000000,2016.000000,4.000000,9.000000,42.297555,-71.097131
50%,2907.000000,2016.000000,7.000000,14.000000,42.325632,-71.077395
75%,3201.000000,2017.000000,10.000000,18.000000,42.348624,-71.062467
max,3831.000000,2017.000000,12.000000,23.000000,42.395042,-1.000000

In [74]:
crime.sort_index(inplace=True)
crime.head()

,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
INCIDENT_NUMBER,,,,,,,,,,,,,,,,
142052550,3125,Warrant Arrests,WARRANT ARREST,D4,903,NaN,2015-06-22 00:12:00,2015,6,Monday,0,Part Three,WASHINGTON ST,42.333839,-71.080290,"(42.33383935, -71.08029038)"
I010370257-00,3125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"
I030217815-08,111,Homicide,"MURDER, NON-NEGLIGIENT MANSLAUGHTER",E18,520,NaN,2015-07-09 13:38:00,2015,7,Thursday,13,Part One,RIVER ST,42.255926,-71.123172,"(42.25592648, -71.12317207)"
I030217815-08,3125,Warrant Arrests,WARRANT ARREST,E18,520,NaN,2015-07-09 13:38:00,2015,7,Thursday,13,Part Three,RIVER ST,42.255926,-71.123172,"(42.25592648, -71.12317207)"
I050310906-00,3125,Warrant Arrests,WARRANT ARREST,D4,285,NaN,2016-06-05 17:25:00,2016,6,Sunday,17,Part Three,COVENTRY ST,42.336951,-71.085748,"(42.33695098, -71.08574813)"

In [46]:
crime.sort_values('DISTRICT').head(15)

,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
OCCURRED_ON_DATE,,,,,,,,,,,,,
2015-06-15 00:00:00,FRAUD - FALSE PRETENSE / SCHEME,A1,93,NaN,2015,6,Monday,0,Part Two,FANEUIL HALL SQ,42.360205,-71.056208,"(42.36020464, -71.05620816)"
2015-10-24 02:08:00,ASSAULT SIMPLE - BATTERY,A1,93,NaN,2015,10,Saturday,2,Part Two,FANEUIL HALL SQ,42.360205,-71.056208,"(42.36020464, -71.05620816)"
2016-09-15 07:25:00,PROPERTY - FOUND,A1,,NaN,2016,9,Thursday,7,Part Three,NaN,NaN,NaN,"(0.00000000, 0.00000000)"
2017-10-23 17:37:00,M/V ACCIDENT - INVOLVING PEDESTRIAN - NO INJURY,A1,,NaN,2017,10,Monday,17,Part Three,OAK ST W,NaN,NaN,"(0.00000000, 0.00000000)"
2017-10-23 17:30:00,LARCENY THEFT FROM BUILDING,A1,,NaN,2017,10,Monday,17,Part One,NaN,NaN,NaN,"(0.00000000, 0.00000000)"
2016-09-15 04:00:00,PROPERTY - FOUND,A1,117,NaN,2016,9,Thursday,4,Part Three,TREMONT ST,42.352023,-71.064634,"(42.35202343, -71.06463445)"
2015-10-24 04:52:00,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,A1,86,NaN,2015,10,Saturday,4,Part Three,CROSS ST,42.363376,-71.057193,"(42.36337600, -71.05719300)"
2016-09-15 03:56:00,ROBBERY - STREET,A1,117,NaN,2016,9,Thursday,3,Part One,WASHINGTON ST,42.351743,-71.062759,"(42.35174282, -71.06275940)"
2016-09-15 03:02:00,VAL - OPERATING AFTER REV/SUSP.,A1,116,NaN,2016,9,Thursday,3,Part Two,ESSEX ST,42.352354,-71.058153,"(42.35235362, -71.05815283)"
2016-09-15 03:01:00,SUDDEN DEATH,A1,114,NaN,2016,9,Thursday,3,Part Three,ATLANTIC AVE,42.354383,-71.052133,"(42.35438252, -71.05213281)"
2015-10-24 07:53:00,DEMONSTRATIONS/RIOT,A1,65,NaN,2015,10,Saturday,7,Part Three,BLOSSOM ST,42.361697,-71.066859,"(42.36169720, -71.06685878)"
2015-10-24 08:00:00,PROPERTY - LOST,A1,77,NaN,2015,10,Saturday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
2016-09-15 01:01:00,INVESTIGATE PROPERTY,A1,82,NaN,2016,9,Thursday,1,Part Three,COMMERCIAL ST,42.367271,-71.052728,"(42.36727100, -71.05272807)"
2016-09-15 00:30:00,M/V - LEAVING SCENE - PROPERTY DAMAGE,A1,116,NaN,2016,9,Thursday,0,Part Three,BEACH ST,42.351084,-71.059395,"(42.35108400, -71.05939500)"
2017-10-23 17:26:00,VANDALISM,A1,86,NaN,2017,10,Monday,17,Part Two,ENDICOTT ST,42.364127,-71.057292,"(42.36412662, -71.05729215)"

In [177]:
crime.sort_values('OCCURRED_ON_DATE', ascending=False).head(15)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
1,I172101688,3301,Verbal Disputes,VERBAL DISPUTE,D4,165,NaN,2017-12-07 21:25:00,2017,12,Thursday,21,Part Three,E BERKELEY ST,42.343228,-71.063431,"(42.34322816, -71.06343087)"
2,I172101687,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,B3,458,NaN,2017-12-07 21:23:00,2017,12,Thursday,21,Part Three,BLUE HILL AVE,42.302389,-71.085394,"(42.30238881, -71.08539388)"
11,I172101671,2629,Harassment,HARASSMENT,E18,501,NaN,2017-12-07 21:08:00,2017,12,Thursday,21,Part Two,HYDE PARK AVE,42.282699,-71.118864,"(42.28269946, -71.11886352)"
3,I172101683,3301,Verbal Disputes,VERBAL DISPUTE,E18,555,NaN,2017-12-07 21:04:00,2017,12,Thursday,21,Part Three,GREW AVE,42.275100,-71.121781,"(42.27510049, -71.12178148)"
4,I172101681,802,Simple Assault,ASSAULT SIMPLE - BATTERY,C11,334,NaN,2017-12-07 20:54:00,2017,12,Thursday,20,Part Two,HENDRY ST,42.309459,-71.065146,"(42.30945933, -71.06514623)"
7,I172101676,3115,Investigate Person,INVESTIGATE PERSON,D4,149,NaN,2017-12-07 20:42:00,2017,12,Thursday,20,Part Three,COLUMBUS AVE,42.345117,-71.076187,"(42.34511650, -71.07618650)"
6,I172101677,3301,Verbal Disputes,VERBAL DISPUTE,B3,450,NaN,2017-12-07 20:32:00,2017,12,Thursday,20,Part Three,WHITFIELD ST,42.292760,-71.074866,"(42.29276044, -71.07486603)"
17,I172101664,613,Larceny,LARCENY SHOPLIFTING,D4,627,NaN,2017-12-07 20:24:00,2017,12,Thursday,20,Part One,KILMARNOCK ST,42.343535,-71.099801,"(42.34353469, -71.09980109)"
18,I172101663,3115,Investigate Person,INVESTIGATE PERSON,B2,603,NaN,2017-12-07 20:22:00,2017,12,Thursday,20,Part Three,TREMONT ST,42.333807,-71.103778,"(42.33380683, -71.10377843)"
15,I172101666,2662,Ballistics,BALLISTICS EVIDENCE/FOUND,B2,294,NaN,2017-12-07 20:14:00,2017,12,Thursday,20,Part Two,AKRON ST,42.325794,-71.085638,"(42.32579408, -71.08563758)"
10,I172101672,3301,Verbal Disputes,VERBAL DISPUTE,C11,342,NaN,2017-12-07 20:07:00,2017,12,Thursday,20,Part Three,GENEVA AVE,42.302886,-71.070561,"(42.30288559, -71.07056121)"
19,I172101662,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,E18,544,NaN,2017-12-07 19:59:00,2017,12,Thursday,19,Part Three,SUMMER ST,42.260896,-71.124887,"(42.26089606, -71.12488672)"
16,I172101665,3115,Investigate Person,INVESTIGATE PERSON,C6,202,NaN,2017-12-07 19:40:00,2017,12,Thursday,19,Part Three,D ST,42.340426,-71.048940,"(42.34042575, -71.04894028)"
29,I172101650,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,NaN,,NaN,2017-12-07 19:16:00,2017,12,Thursday,19,Part Three,NaN,42.346071,-71.084416,"(42.34607130, -71.08441632)"
33,I172101646,3810,Motor Vehicle Accident Response,M/V ACCIDENT - INVOLVING ï¿½BICYCLE - INJURY,D4,141,NaN,2017-12-07 19:08:00,2017,12,Thursday,19,Part Three,MASSACHUSETTS AVE,42.348102,-71.088141,"(42.34810188, -71.08814056)"

In [185]:
crime[0:4]

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I172101695,3301,Verbal Disputes,VERBAL DISPUTE,B2,304,NaN,2017-12-07 18:09:00,2017,12,Thursday,18,Part Three,WASHINGTON ST,42.319440,-71.094675,"(42.31943966, -71.09467467)"
1,I172101688,3301,Verbal Disputes,VERBAL DISPUTE,D4,165,NaN,2017-12-07 21:25:00,2017,12,Thursday,21,Part Three,E BERKELEY ST,42.343228,-71.063431,"(42.34322816, -71.06343087)"
2,I172101687,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,B3,458,NaN,2017-12-07 21:23:00,2017,12,Thursday,21,Part Three,BLUE HILL AVE,42.302389,-71.085394,"(42.30238881, -71.08539388)"
3,I172101683,3301,Verbal Disputes,VERBAL DISPUTE,E18,555,NaN,2017-12-07 21:04:00,2017,12,Thursday,21,Part Three,GREW AVE,42.275100,-71.121781,"(42.27510049, -71.12178148)"

In [186]:
crime_copy = crime.copy()

In [188]:
crime_copy.iloc[0:10, 1:8]

,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE
0,3301,Verbal Disputes,VERBAL DISPUTE,B2,304,NaN,2017-12-07 18:09:00
1,3301,Verbal Disputes,VERBAL DISPUTE,D4,165,NaN,2017-12-07 21:25:00
2,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,B3,458,NaN,2017-12-07 21:23:00
3,3301,Verbal Disputes,VERBAL DISPUTE,E18,555,NaN,2017-12-07 21:04:00
4,802,Simple Assault,ASSAULT SIMPLE - BATTERY,C11,334,NaN,2017-12-07 20:54:00
5,614,Larceny From Motor Vehicle,LARCENY THEFT FROM MV - NON-ACCESSORY,D4,143,NaN,2017-12-07 17:00:00
6,3301,Verbal Disputes,VERBAL DISPUTE,B3,450,NaN,2017-12-07 20:32:00
7,3115,Investigate Person,INVESTIGATE PERSON,D4,149,NaN,2017-12-07 20:42:00
8,3201,Property Lost,PROPERTY - LOST,A1,101,NaN,2017-12-07 18:00:00
9,619,Larceny,LARCENY ALL OTHERS,NaN,,NaN,2017-12-07 18:00:00

In [192]:
crime_copy.iloc[3] # get 3-d row

INCIDENT_NUMBER                         I172101683
OFFENSE_CODE                                  3301
OFFENSE_CODE_GROUP                 Verbal Disputes
OFFENSE_DESCRIPTION                 VERBAL DISPUTE
DISTRICT                                       E18
REPORTING_AREA                                 555
SHOOTING                                       NaN
OCCURRED_ON_DATE               2017-12-07 21:04:00
YEAR                                          2017
MONTH                                           12
DAY_OF_WEEK                               Thursday
HOUR                                            21
UCR_PART                                Part Three
STREET                                    GREW AVE
Lat                                        42.2751
Long                                      -71.1218
Location               (42.27510049, -71.12178148)
Name: 3, dtype: object

In [265]:
# count all incedents in depends on the week day grouped by district - A1
crime_copy.loc[:, ['INCIDENT_NUMBER', 'DISTRICT', 'DAY_OF_WEEK']].groupby(['DISTRICT', 'DAY_OF_WEEK']).count().loc['A1']

             INCIDENT_NUMBER
DAY_OF_WEEK
Friday                  4280
Monday                  3764
Saturday                4337
Sunday                  3697
Thursday                3987
Tuesday                 3780
Wednesday               3859

In [268]:
crime_copy[crime_copy.UCR_PART == 'Part Three'] # get the third part of UCR

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I172101695,3301,Verbal Disputes,VERBAL DISPUTE,B2,304,NaN,2017-12-07 18:09:00,2017,12,Thursday,18,Part Three,WASHINGTON ST,42.319440,-71.094675,"(42.31943966, -71.09467467)"
1,I172101688,3301,Verbal Disputes,VERBAL DISPUTE,D4,165,NaN,2017-12-07 21:25:00,2017,12,Thursday,21,Part Three,E BERKELEY ST,42.343228,-71.063431,"(42.34322816, -71.06343087)"
2,I172101687,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,B3,458,NaN,2017-12-07 21:23:00,2017,12,Thursday,21,Part Three,BLUE HILL AVE,42.302389,-71.085394,"(42.30238881, -71.08539388)"
3,I172101683,3301,Verbal Disputes,VERBAL DISPUTE,E18,555,NaN,2017-12-07 21:04:00,2017,12,Thursday,21,Part Three,GREW AVE,42.275100,-71.121781,"(42.27510049, -71.12178148)"
6,I172101677,3301,Verbal Disputes,VERBAL DISPUTE,B3,450,NaN,2017-12-07 20:32:00,2017,12,Thursday,20,Part Three,WHITFIELD ST,42.292760,-71.074866,"(42.29276044, -71.07486603)"
7,I172101676,3115,Investigate Person,INVESTIGATE PERSON,D4,149,NaN,2017-12-07 20:42:00,2017,12,Thursday,20,Part Three,COLUMBUS AVE,42.345117,-71.076187,"(42.34511650, -71.07618650)"
8,I172101675,3201,Property Lost,PROPERTY - LOST,A1,101,NaN,2017-12-07 18:00:00,2017,12,Thursday,18,Part Three,BROAD ST,42.358245,-71.054154,"(42.35824479, -71.05415356)"
10,I172101672,3301,Verbal Disputes,VERBAL DISPUTE,C11,342,NaN,2017-12-07 20:07:00,2017,12,Thursday,20,Part Three,GENEVA AVE,42.302886,-71.070561,"(42.30288559, -71.07056121)"
12,I172101670,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,C11,235,NaN,2017-12-06 08:00:00,2017,12,Wednesday,8,Part Three,BUTTONWOOD ST,42.319353,-71.055926,"(42.31935305, -71.05592602)"
13,I172101669,3501,Missing Person Reported,MISSING PERSON,A7,19,NaN,2017-11-26 15:30:00,2017,11,Sunday,15,Part Three,SARATOGA ST,42.378648,-71.030892,"(42.37864819, -71.03089238)"
16,I172101665,3115,Investigate Person,INVESTIGATE PERSON,C6,202,NaN,2017-12-07 19:40:00,2017,12,Thursday,19,Part Three,D ST,42.340426,-71.048940,"(42.34042575, -71.04894028)"
18,I172101663,3115,Investigate Person,INVESTIGATE PERSON,B2,603,NaN,2017-12-07 20:22:00,2017,12,Thursday,20,Part Three,TREMONT ST,42.333807,-71.103778,"(42.33380683, -71.10377843)"
19,I172101662,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,E18,544,NaN,2017-12-07 19:59:00,2017,12,Thursday,19,Part Three,SUMMER ST,42.260896,-71.124887,"(42.26089606, -71.12488672)"
24,I172101656,3125,Warrant Arrests,WARRANT ARREST,D4,626,NaN,2017-12-07 18:44:00,2017,12,Thursday,18,Part Three,QUEENSBERRY ST,42.342556,-71.098079,"(42.34255587, -71.09807867)"
26,I172101654,3115,Investigate Person,INVESTIGATE PERSON,C11,337,NaN,2017-12-07 17:33:00,2017,12,Thursday,17,Part Three,COLUMBIA RD,42.309692,-71.072859,"(42.30969169, -71.07285868)"
28,I172101651,3018,Medical Assistance,SICK/INJURED/MEDICAL - POLICE,C11,257,NaN,2017-11-19 16:48:00,2017,11,Sunday,16,Part Three,HANCOCK ST,42.311763,-71.063242,"(42.31176297, -71.06324161)"
29,I172101650,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,NaN,,NaN,2017-12-07 19:16:00,2017,12,Thursday,19,Part Three,NaN,42.346071,-71.084416,"(42.34607130, -71.08441632)"
30,I172101649,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,C11,352,NaN,2017-12-07 19:02:00,2017,12,Thursday,19,Part Three,JOSEPHINE ST,42.300520,-71.064907,"(42.30052010, -71.06490653)"
31,I172101648,3820,Motor Vehicle Accident Response,M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY,A1,116,NaN,2017-12-07 18:58:00,2017,12,Thursday,18,Part Three,BEACH ST,42.351084,-71.059395,"(42.35108400, -71.05939500)"
32,I172101647,3115,Investigate Person,INVESTIGATE PERSON,E13,649,NaN,2017-12-07 18:30:00,2017,12,Thursday,18,Part Three,CUSTER ST,42.307337,-71.116906,"(42.30733666, -71.11690550)"
33,I172101646,3810,Motor Vehicle Accident Response,M/V ACCIDENT - INVOLVING ï¿½BICYCLE - INJURY,D4,141,NaN,2017-12-07 19:08:00,2017,12,Thursday,19,Part Three,MASSACHUSETTS AVE,42.348102,-71.088141,"(42.34810188, -71.08814056)"
34,I172101644,3820,Motor Vehicle Accident Response,M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY,A1,113,NaN,2017-12-07 05:30:00,2017,12,Thursday,5,Part Three,SUMMER ST,42.353877,-71.058302,"(42.35387720, -71.05830207)"
35,I172101642,3301,Verbal Disputes,VERBAL DISPUTE,B2,911,NaN,2017-12-07 18:49:00,2017,12,Thursday,18,Part Three,ANNUNCIATION RD,42.335062,-71.093168,"(42.33506218, -71.09316781)"
43,I172101635,3301,Verbal Disputes,VERBAL DISPUTE,B2,268,NaN,2017-12-07 18:34:54,2017,12,Thursday,18,Part Three,EUSTIS ST,42.329004,-71.078382,"(42.32900380, -71.07838214)"
44,I172101634,3301,Verbal Disputes,VERBAL DISPUTE,B2,304,NaN,2017-12-07 18:07:00,2017,12,Thursday,18,Part Three,ACADEMY TER,42.320822,-71.097315,"(42.32082221, -71.09731506)"
45,I172101631,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D4,903,NaN,2017-12-07 17:42:00,2017,12,Thursday,17,Part Three,HAMMOND ST,42.337052,-71.083767,"(42.33705178, -71.08376738)"
48,I172101629,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY ï¿½DAMAGE,E13,655,NaN,2017-12-07 17:57:00,2017,12,Thursday,17,Part Three,CENTRE ST,42.306787,-71.123835,"(42.30678696, -71.12383470)"
49,I172101628,3803,Motor Vehicle Accident Response,M/V ACCIDENT - PERSONAL INJURY,C11,367,NaN,2017-12-07 16:56:00,2017,12,Thursday,16,Part Three,TRAIN ST,42.290573,-71.053010,"(42.29057318, -71.05301006)"
50,I172101627,3018,Medical Assistance,SICK/INJURED/MEDICAL - POLICE,B3,465,NaN,2017-12-07 18:27:00,2017,12,Thursday,18,Part Three,BLUE HILL AVE,42.284826,-71.091374,"(42.28482577, -71.09137369)"
51,I172101626,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,NaN,,NaN,2017-12-07 13:00:00,2017,12,Thursday,13,Part Three,AMERICAN LEGION,-1.000000,-1.000000,"(-1.00000000, -1.00000000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246100,I130041200-00,3125,Warrant Arrests,WARRANT ARREST,B3,428,NaN,2015-12-07 11:38:00,2015,12,Monday,11,Part Three,DIXWELL ST,42.314334,-71.097914,"(42.31433402, -71.09791405)"
246106,I130041200-00,3125,Warrant Arrests,WARRANT ARREST,B3,428,NaN,2015-12-07 11:38:00,2015,12,Monday,11,Part Three,DIXWELL ST,42.314334,-71.097914,"(42.31433402, -71.09791405)"
246108,I130031413-00,3125,Warrant Arrests,WARRANT ARREST,D4,143,NaN,2015-12-22 21:30:00,2015,12,Tuesday,21,Part Three,BOYLSTON ST,42.349325,-71.080148,"(42.34932471, -71.08014801)"
246112,I120720047-00,3125,Warrant Arrests,WARRANT ARREST,E13,565,NaN,2015-07-17 09:23:00,2015,7,Friday,9,Part Three,NaN,NaN,NaN,"(0.00000000, 0.00000000)"
246117,I120719309-00,3125,Warrant Arrests,WARRANT ARREST,A1,119,NaN,2015-07-27 12:00:00,2015,7,Monday,12,Part Three,BOYLSTON ST,42.352418,-71.065255,"(42.35241815, -71.06525499)"
246119,I120595668-00,3125,Warrant Arrests,WARRANT ARREST,B3,466,NaN,2015-07-02 09:13:00,2015,7,Thursday,9,Part Three,WELLINGTON HILL ST,42.284647,-71.094733,"(42.28464725, -71.09473285)"
246124,I120283195-00,3125,Warrant Arrests,WARRANT ARREST,B2,911,NaN,2016-04-27 00:00:00,2016,4,Wednesday,0,Part Three,ANNUNCIATION RD,42.335062,-71.093168,"(42.33506218, -71.09316781)"
246126,I120260724-01,3125,Warrant Arrests,WARRANT ARREST,A1,105,NaN,2016-09-12 09:00:00,2016,9,Monday,9,Part Three,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)"
246127,I120201612-00,3125,Warrant Arrests,WARRANT ARREST,B2,292,NaN,2017-01-20 02:00:00,2017,1,Friday,2,Part Three,JOHN ELIOT SQ,42.330013,-71.091179,"(42.33001318, -71.09117863)"
246129,I120201612-00,3130,Search Warrants,SEARCH WARRANT,B2,292,NaN,2017-01-20 02:00:00,2017,1,Friday,2,Part Three,JOHN ELIOT SQ,42.330013,-71.091179,"(42.33001318, -71.09117863)"
246130,I120189428-00,3125,Warrant Arrests,WARRANT ARREST,E13,303,NaN,2015-12-09 18:35:00,2015,12,Wednesday,18,Part Three,AMORY ST,42.318245,-71.101268,"(42.31824501, -71.10126771)"
246134,I120069826-00,3125,Warrant Arrests,WARRANT ARREST,D4,597,NaN,2015-10-05 18:01:00,2015,10,Monday,18,Part Three,CAMDEN ST,42.339332,-71.083350,"(42.33933200, -71.08335000)"
246137,I110694557-00,3125,Warrant Arrests,WARRANT ARREST,B3,436,NaN,2016-01-22 09:45:00,2016,1,Friday,9,Part Three,WITHINGTON ST,42.288767,-71.072897,"(42.28876736, -71.07289694)"
246138,I110694557-00,3115,Investigate Person,INVESTIGATE PERSON,B3,436,NaN,2016-01-22 09:45:00,2016,1,Friday,9,Part Three,WITHINGTON ST,42.288767,-71.072897,"(42.28876736, -71.07289694)"
246140,I110551302-00,3125,Warrant Arrests,WARRANT ARREST,D4,171,NaN,2015-07-22 22:00:00,2015,7,Wednesday,22,Part Three,HARRISON AVE,42.335560,-71.074364,"(42.33555954, -71.07436364)"
246141,I110372326-00,3125,Warrant Arrests,WARRANT ARREST,A1,97,NaN,2016-06-14 09:40:00,2016,6,Tuesday,9,Part Three,SCHOOL ST,42.357428,-71.058326,"(42.35742837, -71.05832551)"
246143,I110261417-00,3125,Warrant Arrests,WARRANT ARREST,B2,324,NaN,2016-07-29 00:00:00,2016,7,Friday,0,Part Three,BOWDOIN ST,42.307038,-71.066153,"(42.30703835, -71.06615319)"
246145,I110177502-00,3125,Warrant Arrests,WARRANT ARREST,B2,318,NaN,2015-10-02 21:00:00,2015,10,Friday,21,Part Three,HOMESTEAD ST,42.311277,-71.089093,"(42.31127726, -71.08909334)"
246147,I110177502-00,3125,Warrant Arrests,WARRANT ARREST,B2,318,NaN,2015-10-02 21:00:00,2015,10,Friday,21,Part Three,HOMESTEAD ST,42.311277,-71.089093,"(42.31127726, -71.08909334)"
246149,I100636670-00,3125,Warrant Arrests,WARRANT ARREST,D4,285,NaN,2016-06-05 17:23:00,2016,6,Sunday,17,Part Three,COVENTRY ST,42.336951,-71.085748,"(42.33695098, -71.08574813)"
246150,I100340225-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2015-07-27 10:47:00,2015,7,Monday,10,Part Three,BOWDOIN SQ,42.361645,-71.062299,"(42.36164502, -71.06229949)"
246152,I100222105-02,3125,Warrant Arrests,WARRANT ARREST,E13,572,NaN,2015-08-03 16:22:00,2015,8,Monday,16,Part Three,COLUMBUS AVE,42.313628,-71.095603,"(42.31362799, -71.09560307)"
246155,I090321958-00,3125,Warrant Arrests,WARRANT ARREST,C11,355,NaN,2016-02-01 01:43:00,2016,2,Monday,1,Part Three,GENEVA AVE,NaN,NaN,"(0.00000000, 0.00000000)"
246156,I090321958-00,3125,Warrant Arrests,WARRANT ARREST,C11,355,NaN,2016-02-01 01:43:00,2016,2,Monday,1,Part Three,GENEVA AVE,NaN,NaN,"(0.00000000, 0.00000000)"
246158,I090317057-00,3125,Warrant Arrests,WARRANT ARREST,B3,458,NaN,2015-11-20 11:15:00,2015,11,Friday,11,Part Three,BLUE HILL AVE,42.301897,-71.085549,"(42.30189690, -71.08554944)"
246159,I080542626-00,3125,Warrant Arrests,WARRANT ARREST,A1,111,NaN,2015-08-12 12:00:00,2015,8,Wednesday,12,Part Three,BOYLSTON ST,42.352312,-71.063705,"(42.35231190, -71.06370510)"
246162,I050310906-00,3125,Warrant Arrests,WARRANT ARREST,D4,285,NaN,2016-06-05 17:25:00,2016,6,Sunday,17,Part Three,COVENTRY ST,42.336951,-71.085748,"(42.33695098, -71.08574813)"
246164,I030217815-08,3125,Warrant Arrests,WARRANT ARREST,E18,520,NaN,2015-07-09 13:38:00,2015,7,Thursday,13,Part Three,RIVER ST,42.255926,-71.123172,"(42.25592648, -71.12317207)"
246165,I010370257-00,3125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"
246166,142052550,3125,Warrant Arrests,WARRANT ARREST,D4,903,NaN,2015-06-22 00:12:00,2015,6,Monday,0,Part Three,WASHINGTON ST,42.333839,-71.080290,"(42.33383935, -71.08029038)"